### ISSUE TITLE
Using Flask-Cache (obs.); need to use Flask-Caching

### ISSUE THREAD

**Issue by lily-mayfield** [opensyllabus/osp-api#4]
`flask-cache` is obsolete (not maintained). Use `Flask-Caching` which has the same API (new maintainer).

Something to contemplate: will `Flask-Caching` be better about query string parameter order thus making my `make_cache_key()` obsolete? Good thing I wrote tests to find out (I can find out!)!

**Comment by lily-mayfield** [comment]
I tested it with and without my `make_cache_key()`: it definitely needs it. So no time wasted there!

Maybe we can get the author of `flask-caching` (@thadeusb) to upstream this: https://github.com/opensyllabus/osp-api/blob/master/osp_api/util.py#L6

**Comment by lily-mayfield** [comment]
I tested it with and without my `make_cache_key()`: it definitely needs it. So no time wasted there!

Maybe we can get the author of `flask-caching` (@sh4nks) to upstream this: https://github.com/opensyllabus/osp-api/blob/master/osp_api/util.py#L6

**Comment by sh4nks** [comment]
Hey!

That would be a cool enhancement. Could you open a PR with a little test for it? I'll merge it then :)
